name: Deploy / Atualizar Servidores
run-name: Deploy do artefato ${{ inputs.releasetag }} em ${{ inputs.ambiente }} disparada por ${{ github.actor }}

on:
  workflow_dispatch:
    inputs:
      releasetag:
        description: "Nome do artefato/versão"
        type: string
        required: true
      ambiente:
        type: choice
        description: 'Ambiente'
        required: true
        default: 'TST'
        options:
        - TST
        - PRD

jobs:
  app_publish:
    runs-on: ubuntu-latest
    steps:
      # Baixa a release informada
      - name: Download Release
        uses: dsaltares/fetch-gh-release-asset@master
        with:
          repo: 'rap1986/planner'
          version: "tags/${{ github.event.inputs.releasetag }}"
          file: 'artefatos.zip'
          token: ${{ secrets.GITHUB_TOKEN }}
      # Descompacta backend
      - name: Descompact Zip
        shell: bash
        run: unzip artefatos.zip 
      # SSH Key
      - name: Baixa KeyPair
        run: |
          echo "${{ secrets.KEYPAIR_PEM }}" > keypair.pem
          sudo chmod 400 keypair.pem
      - name: Adiciona ao known_hosts
        shell: bash
        run: |
          mkdir -p ~/.ssh/
          ssh-keyscan -H $(echo ${{ secrets.URL_TST }} | sed 's/.*@//') >> ~/.ssh/known_hosts
          ssh-keyscan -H $(echo ${{ secrets.URL_PRD }} | sed 's/.*@//') >> ~/.ssh/known_hosts
          sudo chmod 600 ~/.ssh/known_hosts
      #Atualiza servidor
      - name: Atualiza em TST
        if: ${{ inputs.ambiente == 'TST' }}
        run: |
          rsync -e "ssh -i keypair.pem" -avz build/backend/* ${{ secrets.URL_TST }}:${{ secrets.HOST_FOLDER }}/backend
          rsync -e "ssh -i keypair.pem" -avz build/frontend/* ${{ secrets.URL_TST }}:${{ secrets.HOST_FOLDER }}/frontend
      #Atualiza Produção
      - name: Atualiza em PRD
        if: ${{ inputs.ambiente == 'PRD' }}
        run: |
          rsync -e "ssh -i keypair.pem" -avz build/backend/* ${{ secrets.URL_PRD }}:${{ secrets.HOST_FOLDER }}/backend
          rsync -e "ssh -i keypair.pem" -avz build/frontend/* ${{ secrets.URL_PRD }}:${{ secrets.HOST_FOLDER }}/frontend